# config.yaml

paths:
  input_dir: "../input/archive"
  output_dir: "../output"

elo:
  start: 1000
  K_below_1200: 192
  K_below_1600: 96
  K_below_2000: 40
  K_above: 16
  floor: 0
  C_low: 0.5
  C_medium: 1.0
  C_high: 1.5
  
